title: "Welcome to Business Analytics (MGT 4050)!"

theme: jekyll-theme-minimal

description:  > 
"By Zhaohu (Jonathan) Fan <br /> ''Where Business Meets Dataâ€”and Decisions Get Smarter.''" 

show_downloads: false
github:
  is_project_page: false
